language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  include:
    # This builder only tests code linters on latest version of Go
    - stage: lint
      os: linux
      dist: bionic
      go: 1.16.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint

    - stage: test A-B packages
      os: linux
      dist: bionic
      go: 1.15.x
      env:
        - GO111MODULE=auto
      script:
        - go run build/ci.go test -coverage $(go list ./... | grep "github.com\/ethereum\/go-ethereum\/[a-b].*")

    - stage: test C packages
      os: linux
      dist: bionic
      go: 1.15.x
      env:
        - GO111MODULE=auto
      script:
        - go run build/ci.go test -coverage $(go list ./... | grep "github.com\/ethereum\/go-ethereum\/[c].*")

    - stage: test D-N packages
      os: linux
      dist: bionic
      go: 1.15.x
      env:
        - GO111MODULE=auto
      script:
        - go run build/ci.go test -coverage $(go list ./... | grep "github.com\/ethereum\/go-ethereum\/[d-n].*")
    
    - stage: test O-R packages
      os: linux
      dist: bionic
      go: 1.15.x
      env:
        - GO111MODULE=auto
      script:
        - go run build/ci.go test -coverage $(go list ./... | grep "github.com\/ethereum\/go-ethereum\/[o-r].*")

    - stage: test S-Z packages
      os: linux
      dist: bionic
      go: 1.15.x
      env:
        - GO111MODULE=auto
      script:
        - go run build/ci.go test -coverage $(go list ./... | grep "github.com\/ethereum\/go-ethereum\/[s-z].*")